cors:
  allow_origin:
    - "http://localhost:3000"
    - "http://127.0.0.1:3000"
    - "http://localhost:5173"
    - "http://127.0.0.1:5173"
    - "https://e-tawjihi.ma"
    - "https://www.e-tawjihi.ma"
    - "https://e-tawjihi.com"
    - "https://www.e-tawjihi.com"
    - "http://e-tawjihi.ma"
    - "http://www.e-tawjihi.ma"
    - "http://e-tawjihi.com"
    - "http://www.e-tawjihi.com"
  allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS", "PATCH"]
  allow_headers: ["Content-Type", "Authorization", "X-Requested-With", "Accept"]
  allow_credentials: true
  max_age: 3600
