<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251030174835 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE agent_assignments (id INT AUTO_INCREMENT NOT NULL, student_id INT NOT NULL, agent_id INT NOT NULL, application_id INT DEFAULT NULL, status VARCHAR(20) NOT NULL, agent_code VARCHAR(50) DEFAULT NULL, notes LONGTEXT DEFAULT NULL, assigned_at DATETIME NOT NULL, completed_at DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_A0440B9DCB944F1A (student_id), INDEX IDX_A0440B9D3414710B (agent_id), INDEX IDX_A0440B9D3E030ACD (application_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ambassadors (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, university VARCHAR(100) NOT NULL, field_of_study VARCHAR(50) NOT NULL, study_level VARCHAR(20) NOT NULL, graduation_year INT NOT NULL, motivation LONGTEXT NOT NULL, experience LONGTEXT NOT NULL, skills LONGTEXT NOT NULL, social_media LONGTEXT DEFAULT NULL, additional_info LONGTEXT DEFAULT NULL, status VARCHAR(20) NOT NULL, admin_notes LONGTEXT DEFAULT NULL, interview_date DATETIME DEFAULT NULL, training_date DATETIME DEFAULT NULL, start_date DATETIME DEFAULT NULL, end_date DATETIME DEFAULT NULL, points INT NOT NULL, referrals INT NOT NULL, is_active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_67BE424CA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE application_documents (id INT AUTO_INCREMENT NOT NULL, application_id INT NOT NULL, reviewed_by_id INT DEFAULT NULL, document_type VARCHAR(50) NOT NULL, file_name VARCHAR(255) NOT NULL, file_path VARCHAR(500) NOT NULL, mime_type VARCHAR(50) NOT NULL, file_size INT NOT NULL, status VARCHAR(20) NOT NULL, notes LONGTEXT DEFAULT NULL, rejection_reason LONGTEXT DEFAULT NULL, uploaded_at DATETIME NOT NULL, reviewed_at DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_26B108893E030ACD (application_id), INDEX IDX_26B10889FC6B21F1 (reviewed_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE application_steps (id INT AUTO_INCREMENT NOT NULL, application_id INT NOT NULL, step_number INT NOT NULL, step_name VARCHAR(100) NOT NULL, step_title VARCHAR(255) DEFAULT NULL, description LONGTEXT DEFAULT NULL, is_completed TINYINT(1) NOT NULL, completed_at DATETIME DEFAULT NULL, step_data JSON DEFAULT NULL, notes LONGTEXT DEFAULT NULL, required_documents JSON DEFAULT NULL, validation_errors JSON DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_D7B6ED083E030ACD (application_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE applications (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, program_id INT NOT NULL, user_profile_id INT DEFAULT NULL, status VARCHAR(50) NOT NULL, agent_id INT DEFAULT NULL, current_step INT NOT NULL, progress_percentage NUMERIC(5, 2) NOT NULL, notes LONGTEXT DEFAULT NULL, application_data JSON NOT NULL, submitted_data JSON DEFAULT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', submitted_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', is_china TINYINT(1) DEFAULT NULL, is_france TINYINT(1) DEFAULT NULL, passport_number VARCHAR(50) DEFAULT NULL, passport_issue_date VARCHAR(50) DEFAULT NULL, passport_expiration_date VARCHAR(50) DEFAULT NULL, religion VARCHAR(255) DEFAULT NULL, family_members JSON DEFAULT NULL, INDEX IDX_F7C966F0A76ED395 (user_id), INDEX IDX_F7C966F03EB8070A (program_id), INDEX IDX_F7C966F06B9DD454 (user_profile_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE complaint_messages (id INT AUTO_INCREMENT NOT NULL, complaint_id INT NOT NULL, sender_id INT NOT NULL, message LONGTEXT NOT NULL, attachments JSON DEFAULT NULL, is_from_admin TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, INDEX IDX_C71B3714EDAE188E (complaint_id), INDEX IDX_C71B3714F624B39D (sender_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE complaints (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, category VARCHAR(50) NOT NULL, subject VARCHAR(100) NOT NULL, description LONGTEXT NOT NULL, priority VARCHAR(20) NOT NULL, status VARCHAR(20) NOT NULL, attachments JSON DEFAULT NULL, related_service VARCHAR(50) DEFAULT NULL, related_document VARCHAR(50) DEFAULT NULL, related_test VARCHAR(50) DEFAULT NULL, admin_response LONGTEXT DEFAULT NULL, admin_response_date DATETIME DEFAULT NULL, admin_user_id INT DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_A05AAF3AA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE document_translations (id INT AUTO_INCREMENT NOT NULL, original_document_id INT NOT NULL, target_language VARCHAR(255) NOT NULL, filename VARCHAR(255) NOT NULL, original_filename VARCHAR(255) NOT NULL, mime_type VARCHAR(100) NOT NULL, file_size INT NOT NULL, status VARCHAR(50) NOT NULL, notes LONGTEXT DEFAULT NULL, etawjihi_notes LONGTEXT DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, completed_at DATETIME DEFAULT NULL, INDEX IDX_6B52FBF63430981D (original_document_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE documents (id INT AUTO_INCREMENT NOT NULL, user_profile_id INT NOT NULL, type VARCHAR(50) NOT NULL, category VARCHAR(50) NOT NULL, title VARCHAR(255) NOT NULL, filename VARCHAR(255) NOT NULL, original_filename VARCHAR(255) NOT NULL, mime_type VARCHAR(50) NOT NULL, file_size INT NOT NULL, status VARCHAR(20) NOT NULL, description LONGTEXT DEFAULT NULL, expiry_date DATE DEFAULT NULL, rejection_reason LONGTEXT DEFAULT NULL, validation_status VARCHAR(20) DEFAULT NULL, validation_notes LONGTEXT DEFAULT NULL, validated_by VARCHAR(255) DEFAULT NULL, validated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', original_language VARCHAR(255) DEFAULT NULL, etawjihi_notes LONGTEXT DEFAULT NULL, INDEX IDX_A2B072886B9DD454 (user_profile_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE establishments (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, name_fr VARCHAR(255) DEFAULT NULL, slug VARCHAR(255) NOT NULL, country VARCHAR(255) DEFAULT NULL, city VARCHAR(255) DEFAULT NULL, type VARCHAR(100) DEFAULT NULL, rating NUMERIC(3, 1) DEFAULT NULL, students INT DEFAULT NULL, programs INT DEFAULT NULL, logo VARCHAR(500) DEFAULT NULL, description LONGTEXT DEFAULT NULL, description_fr LONGTEXT DEFAULT NULL, mission LONGTEXT DEFAULT NULL, mission_fr LONGTEXT DEFAULT NULL, founded_year INT DEFAULT NULL, featured TINYINT(1) NOT NULL, sponsored TINYINT(1) NOT NULL, tuition VARCHAR(255) DEFAULT NULL, tuition_min NUMERIC(10, 2) DEFAULT NULL, tuition_max NUMERIC(10, 2) DEFAULT NULL, tuition_currency VARCHAR(10) DEFAULT NULL, acceptance_rate VARCHAR(10) DEFAULT NULL, world_ranking INT DEFAULT NULL, qs_ranking INT DEFAULT NULL, times_ranking INT DEFAULT NULL, arwu_ranking INT DEFAULT NULL, us_news_ranking INT DEFAULT NULL, popular_programs JSON DEFAULT NULL, application_deadline DATE DEFAULT NULL, scholarships TINYINT(1) NOT NULL, scholarship_types JSON DEFAULT NULL, scholarship_description LONGTEXT DEFAULT NULL, housing TINYINT(1) NOT NULL, language VARCHAR(50) DEFAULT NULL, aidvisor_recommended TINYINT(1) NOT NULL, easy_apply TINYINT(1) NOT NULL, university_type VARCHAR(10) DEFAULT NULL, commission_rate VARCHAR(20) DEFAULT NULL, free_applications INT DEFAULT NULL, visa_support VARCHAR(20) DEFAULT NULL, country_specific JSON DEFAULT NULL, website VARCHAR(500) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, phone VARCHAR(50) DEFAULT NULL, address LONGTEXT DEFAULT NULL, accreditations JSON DEFAULT NULL, accommodation TINYINT(1) NOT NULL, career_services TINYINT(1) NOT NULL, language_support TINYINT(1) NOT NULL, is_active TINYINT(1) NOT NULL, admission_requirements JSON DEFAULT NULL, admission_requirements_fr JSON DEFAULT NULL, english_test_requirements JSON DEFAULT NULL, academic_requirements JSON DEFAULT NULL, document_requirements JSON DEFAULT NULL, visa_requirements JSON DEFAULT NULL, application_fee NUMERIC(10, 2) DEFAULT NULL, application_fee_currency VARCHAR(10) DEFAULT NULL, living_costs NUMERIC(10, 2) DEFAULT NULL, living_costs_currency VARCHAR(10) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, languages JSON DEFAULT NULL, youtube_videos JSON DEFAULT NULL, brochures JSON DEFAULT NULL, campus_locations JSON DEFAULT NULL, campus_photos JSON DEFAULT NULL, status VARCHAR(20) DEFAULT NULL, seo_title VARCHAR(255) DEFAULT NULL, seo_description LONGTEXT DEFAULT NULL, seo_keywords JSON DEFAULT NULL, seo_image_alt LONGTEXT DEFAULT NULL, service_pricing JSON DEFAULT NULL, multi_intakes JSON DEFAULT NULL, UNIQUE INDEX UNIQ_5C67EFC5989D9B62 (slug), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE faqs (id INT AUTO_INCREMENT NOT NULL, category VARCHAR(50) NOT NULL, question VARCHAR(200) NOT NULL, question_fr VARCHAR(200) NOT NULL, answer LONGTEXT NOT NULL, answer_fr LONGTEXT NOT NULL, sort_order INT NOT NULL, is_active TINYINT(1) NOT NULL, is_popular TINYINT(1) NOT NULL, icon VARCHAR(20) DEFAULT NULL, color VARCHAR(20) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE final_step_documents (id INT AUTO_INCREMENT NOT NULL, final_step_id INT NOT NULL, title VARCHAR(255) NOT NULL, title_en VARCHAR(255) NOT NULL, title_fr VARCHAR(255) NOT NULL, file_path VARCHAR(500) NOT NULL, file_type VARCHAR(100) NOT NULL, file_size INT DEFAULT NULL, is_active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_F1DCBC54F09195D0 (final_step_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE final_steps (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, name_en VARCHAR(255) NOT NULL, name_fr VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, description_en LONGTEXT DEFAULT NULL, description_fr LONGTEXT DEFAULT NULL, step_order INT NOT NULL, is_active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE modification_requests (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, application_id INT NOT NULL, admin_id INT DEFAULT NULL, reason LONGTEXT NOT NULL, status VARCHAR(20) NOT NULL, admin_response LONGTEXT DEFAULT NULL, modification_allowed_until DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, responded_at DATETIME DEFAULT NULL, INDEX IDX_46C9571DA76ED395 (user_id), INDEX IDX_46C9571D3E030ACD (application_id), INDEX IDX_46C9571D642B8210 (admin_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE parameters (id INT AUTO_INCREMENT NOT NULL, category VARCHAR(64) NOT NULL, code VARCHAR(128) NOT NULL, label_en VARCHAR(255) NOT NULL, label_fr VARCHAR(255) NOT NULL, description_en VARCHAR(1000) DEFAULT NULL, description_fr VARCHAR(1000) DEFAULT NULL, score_range VARCHAR(255) DEFAULT NULL, meta JSON DEFAULT NULL, parent_code VARCHAR(128) DEFAULT NULL, is_active TINYINT(1) DEFAULT 1 NOT NULL, sort_order INT DEFAULT 0 NOT NULL, UNIQUE INDEX uniq_param_category_code (category, code), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE preferences (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, preferred_destinations JSON DEFAULT NULL, preferred_study_level VARCHAR(50) DEFAULT NULL, preferred_degree VARCHAR(50) DEFAULT NULL, preferred_intakes JSON DEFAULT NULL, preferred_subjects JSON DEFAULT NULL, preferred_currency VARCHAR(10) DEFAULT NULL, annual_budget JSON DEFAULT NULL, scholarship_required TINYINT(1) DEFAULT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', UNIQUE INDEX UNIQ_E931A6F5A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE program_requirements (id INT AUTO_INCREMENT NOT NULL, program_id INT NOT NULL, type VARCHAR(100) NOT NULL, subtype VARCHAR(100) DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, description LONGTEXT DEFAULT NULL, minimum_value NUMERIC(10, 2) DEFAULT NULL, maximum_value NUMERIC(10, 2) DEFAULT NULL, unit VARCHAR(50) DEFAULT NULL, `system` VARCHAR(50) DEFAULT NULL, is_required TINYINT(1) NOT NULL, is_active TINYINT(1) NOT NULL, metadata JSON DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_331B528D3EB8070A (program_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE programs (id INT AUTO_INCREMENT NOT NULL, establishment_id INT NOT NULL, name VARCHAR(255) NOT NULL, name_fr VARCHAR(255) DEFAULT NULL, slug VARCHAR(255) DEFAULT NULL, description LONGTEXT DEFAULT NULL, description_fr LONGTEXT DEFAULT NULL, curriculum JSON DEFAULT NULL, curriculum_fr LONGTEXT DEFAULT NULL, country VARCHAR(255) DEFAULT NULL, city VARCHAR(255) DEFAULT NULL, degree VARCHAR(100) DEFAULT NULL, duration VARCHAR(50) DEFAULT NULL, duration_unit VARCHAR(10) DEFAULT NULL, language VARCHAR(50) DEFAULT NULL, tuition VARCHAR(255) DEFAULT NULL, tuition_amount NUMERIC(10, 2) DEFAULT NULL, tuition_currency VARCHAR(10) DEFAULT NULL, start_date DATE DEFAULT NULL, start_year VARCHAR(4) DEFAULT NULL, intake VARCHAR(20) DEFAULT NULL, application_deadline DATE DEFAULT NULL, scholarships TINYINT(1) NOT NULL, logo VARCHAR(500) DEFAULT NULL, featured TINYINT(1) NOT NULL, aidvisor_recommended TINYINT(1) NOT NULL, easy_apply TINYINT(1) NOT NULL, housing TINYINT(1) NOT NULL, oral_exam TINYINT(1) NOT NULL, written_exam TINYINT(1) NOT NULL, ranking INT DEFAULT NULL, study_type VARCHAR(50) DEFAULT NULL, university_type VARCHAR(10) DEFAULT NULL, subject VARCHAR(100) DEFAULT NULL, field JSON DEFAULT NULL, study_level VARCHAR(50) DEFAULT NULL, languages JSON DEFAULT NULL, intakes JSON DEFAULT NULL, subjects JSON DEFAULT NULL, study_levels JSON DEFAULT NULL, career_prospects LONGTEXT DEFAULT NULL, faculty JSON DEFAULT NULL, facilities JSON DEFAULT NULL, accreditations JSON DEFAULT NULL, rating NUMERIC(3, 1) DEFAULT NULL, reviews INT DEFAULT NULL, is_active TINYINT(1) NOT NULL, academic_qualifications JSON DEFAULT NULL, grade_requirements JSON DEFAULT NULL, minimum_grade NUMERIC(5, 2) DEFAULT NULL, grade_system VARCHAR(50) DEFAULT NULL, requires_academic_qualification TINYINT(1) NOT NULL, gpa_scale VARCHAR(50) DEFAULT NULL, gpa_score NUMERIC(5, 2) DEFAULT NULL, requires_gpa TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, structured_requirements JSON DEFAULT NULL, status VARCHAR(20) DEFAULT \'draft\' NOT NULL, campus_photos JSON DEFAULT NULL, campus_locations JSON DEFAULT NULL, youtube_videos JSON DEFAULT NULL, brochures JSON DEFAULT NULL, seo_title VARCHAR(255) DEFAULT NULL, seo_description LONGTEXT DEFAULT NULL, seo_keywords JSON DEFAULT NULL, multi_intakes JSON DEFAULT NULL, service_pricing JSON DEFAULT NULL, program_type VARCHAR(10) DEFAULT NULL, INDEX IDX_F14965458565851 (establishment_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE qualifications (id INT AUTO_INCREMENT NOT NULL, user_profile_id INT NOT NULL, type VARCHAR(50) NOT NULL, title VARCHAR(255) NOT NULL, institution VARCHAR(255) DEFAULT NULL, field VARCHAR(255) DEFAULT NULL, start_date DATE DEFAULT NULL, end_date DATE DEFAULT NULL, grade VARCHAR(50) DEFAULT NULL, score NUMERIC(5, 2) DEFAULT NULL, score_type VARCHAR(50) DEFAULT NULL, description LONGTEXT DEFAULT NULL, detailed_scores JSON DEFAULT NULL, country VARCHAR(100) DEFAULT NULL, board VARCHAR(255) DEFAULT NULL, grading_scheme VARCHAR(50) DEFAULT NULL, english_score NUMERIC(5, 2) DEFAULT NULL, academic_qualification VARCHAR(100) DEFAULT NULL, exact_qualification_name VARCHAR(255) DEFAULT NULL, baccalaureate_stream VARCHAR(100) DEFAULT NULL, baccalaureate_stream_other VARCHAR(255) DEFAULT NULL, expiry_date DATE DEFAULT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_6765324C6B9DD454 (user_profile_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE services (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(100) NOT NULL, name_fr VARCHAR(100) NOT NULL, description LONGTEXT NOT NULL, description_fr LONGTEXT NOT NULL, price NUMERIC(10, 2) NOT NULL, currency VARCHAR(3) NOT NULL, category VARCHAR(50) NOT NULL, target_countries JSON NOT NULL, features JSON NOT NULL, features_fr JSON NOT NULL, icon VARCHAR(10) NOT NULL, color VARCHAR(20) NOT NULL, is_active TINYINT(1) NOT NULL, duration INT DEFAULT NULL, duration_unit VARCHAR(50) DEFAULT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE shortlists (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, program_id INT DEFAULT NULL, establishment_id INT DEFAULT NULL, user_profile_id INT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_35C4212BA76ED395 (user_id), INDEX IDX_35C4212B3EB8070A (program_id), INDEX IDX_35C4212B8565851 (establishment_id), INDEX IDX_35C4212B6B9DD454 (user_profile_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE suggestions (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, category VARCHAR(50) NOT NULL, title VARCHAR(200) NOT NULL, description LONGTEXT NOT NULL, priority VARCHAR(20) NOT NULL, status VARCHAR(20) NOT NULL, attachments JSON DEFAULT NULL, admin_response LONGTEXT DEFAULT NULL, admin_response_date DATETIME DEFAULT NULL, admin_user_id INT DEFAULT NULL, votes INT NOT NULL, is_public TINYINT(1) NOT NULL, is_anonymous TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_91B68614A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE test_vouchers (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(100) NOT NULL, name_fr VARCHAR(100) NOT NULL, vendor VARCHAR(50) NOT NULL, vendor_logo VARCHAR(255) NOT NULL, original_price NUMERIC(10, 2) NOT NULL, discounted_price NUMERIC(10, 2) NOT NULL, currency VARCHAR(3) NOT NULL, category VARCHAR(20) NOT NULL, status VARCHAR(20) NOT NULL, description LONGTEXT NOT NULL, description_fr LONGTEXT NOT NULL, recognition LONGTEXT NOT NULL, recognition_fr LONGTEXT NOT NULL, features JSON NOT NULL, features_fr JSON NOT NULL, validity VARCHAR(50) NOT NULL, validity_fr VARCHAR(50) NOT NULL, share_link VARCHAR(255) DEFAULT NULL, buy_link VARCHAR(255) DEFAULT NULL, icon VARCHAR(10) NOT NULL, color VARCHAR(20) NOT NULL, is_active TINYINT(1) NOT NULL, sort_order INT DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE translations (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, original_filename VARCHAR(255) NOT NULL, original_file_path VARCHAR(255) NOT NULL, original_language VARCHAR(10) NOT NULL, target_language VARCHAR(10) NOT NULL, document_type VARCHAR(50) NOT NULL, number_of_pages INT NOT NULL, price_per_page NUMERIC(10, 2) NOT NULL, total_price NUMERIC(10, 2) NOT NULL, currency VARCHAR(10) NOT NULL, status VARCHAR(20) NOT NULL, payment_status VARCHAR(20) NOT NULL, notes LONGTEXT DEFAULT NULL, translated_file_path VARCHAR(255) DEFAULT NULL, translated_filename VARCHAR(255) DEFAULT NULL, delivery_date DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_C6B7DA87A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE `user` (id INT AUTO_INCREMENT NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, first_name VARCHAR(255) DEFAULT NULL, last_name VARCHAR(255) DEFAULT NULL, preferred_language VARCHAR(5) DEFAULT NULL, UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL (email), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_final_step_status (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, final_step_id INT NOT NULL, status VARCHAR(50) NOT NULL, notes LONGTEXT DEFAULT NULL, completed_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_58BBA552A76ED395 (user_id), INDEX IDX_58BBA552F09195D0 (final_step_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_profiles (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, first_name VARCHAR(255) DEFAULT NULL, last_name VARCHAR(255) DEFAULT NULL, country VARCHAR(255) DEFAULT NULL, city VARCHAR(255) DEFAULT NULL, nationality JSON DEFAULT NULL, phone VARCHAR(20) DEFAULT NULL, whatsapp VARCHAR(20) DEFAULT NULL, phone_country VARCHAR(10) DEFAULT NULL, whatsapp_country VARCHAR(10) DEFAULT NULL, passport_number VARCHAR(50) DEFAULT NULL, passport_expiration_date DATE DEFAULT NULL, cin_number VARCHAR(50) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, gender VARCHAR(50) DEFAULT NULL, marital_status VARCHAR(50) DEFAULT NULL, country_of_birth VARCHAR(255) DEFAULT NULL, city_of_birth VARCHAR(255) DEFAULT NULL, alternate_email VARCHAR(255) DEFAULT NULL, religion VARCHAR(100) DEFAULT NULL, native_language VARCHAR(100) DEFAULT NULL, chinese_name VARCHAR(255) DEFAULT NULL, wechat_id VARCHAR(100) DEFAULT NULL, skype_no VARCHAR(100) DEFAULT NULL, emergency_contact_name VARCHAR(255) DEFAULT NULL, emergency_contact_gender VARCHAR(50) DEFAULT NULL, emergency_contact_relationship VARCHAR(50) DEFAULT NULL, emergency_contact_phone VARCHAR(50) DEFAULT NULL, emergency_contact_email VARCHAR(255) DEFAULT NULL, emergency_contact_address LONGTEXT DEFAULT NULL, has_work_experience TINYINT(1) DEFAULT NULL, work_company VARCHAR(255) DEFAULT NULL, work_position VARCHAR(255) DEFAULT NULL, work_start_date DATE DEFAULT NULL, work_end_date DATE DEFAULT NULL, work_description LONGTEXT DEFAULT NULL, address LONGTEXT DEFAULT NULL, postal_code VARCHAR(20) DEFAULT NULL, date_of_birth DATE DEFAULT NULL, avatar VARCHAR(255) DEFAULT NULL, study_level VARCHAR(50) DEFAULT NULL, field_of_study VARCHAR(255) DEFAULT NULL, preferred_country VARCHAR(255) DEFAULT NULL, start_date VARCHAR(50) DEFAULT NULL, preferred_currency VARCHAR(10) DEFAULT NULL, annual_budget NUMERIC(10, 2) DEFAULT NULL, scholarship_required TINYINT(1) DEFAULT NULL, language_preferences JSON DEFAULT NULL, onboarding_progress JSON DEFAULT NULL, step2_validated TINYINT(1) DEFAULT NULL, step4_validated TINYINT(1) DEFAULT NULL, step5_validated TINYINT(1) DEFAULT NULL, preferred_destinations JSON DEFAULT NULL, preferred_intakes JSON DEFAULT NULL, preferred_subjects JSON DEFAULT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', UNIQUE INDEX UNIQ_6BBD6130A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE agent_assignments ADD CONSTRAINT FK_A0440B9DCB944F1A FOREIGN KEY (student_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE agent_assignments ADD CONSTRAINT FK_A0440B9D3414710B FOREIGN KEY (agent_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE agent_assignments ADD CONSTRAINT FK_A0440B9D3E030ACD FOREIGN KEY (application_id) REFERENCES applications (id)');
        $this->addSql('ALTER TABLE ambassadors ADD CONSTRAINT FK_67BE424CA76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE application_documents ADD CONSTRAINT FK_26B108893E030ACD FOREIGN KEY (application_id) REFERENCES applications (id)');
        $this->addSql('ALTER TABLE application_documents ADD CONSTRAINT FK_26B10889FC6B21F1 FOREIGN KEY (reviewed_by_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE application_steps ADD CONSTRAINT FK_D7B6ED083E030ACD FOREIGN KEY (application_id) REFERENCES applications (id)');
        $this->addSql('ALTER TABLE applications ADD CONSTRAINT FK_F7C966F0A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE applications ADD CONSTRAINT FK_F7C966F03EB8070A FOREIGN KEY (program_id) REFERENCES programs (id)');
        $this->addSql('ALTER TABLE applications ADD CONSTRAINT FK_F7C966F06B9DD454 FOREIGN KEY (user_profile_id) REFERENCES user_profiles (id)');
        $this->addSql('ALTER TABLE complaint_messages ADD CONSTRAINT FK_C71B3714EDAE188E FOREIGN KEY (complaint_id) REFERENCES complaints (id)');
        $this->addSql('ALTER TABLE complaint_messages ADD CONSTRAINT FK_C71B3714F624B39D FOREIGN KEY (sender_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE complaints ADD CONSTRAINT FK_A05AAF3AA76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE document_translations ADD CONSTRAINT FK_6B52FBF63430981D FOREIGN KEY (original_document_id) REFERENCES documents (id)');
        $this->addSql('ALTER TABLE documents ADD CONSTRAINT FK_A2B072886B9DD454 FOREIGN KEY (user_profile_id) REFERENCES user_profiles (id)');
        $this->addSql('ALTER TABLE final_step_documents ADD CONSTRAINT FK_F1DCBC54F09195D0 FOREIGN KEY (final_step_id) REFERENCES final_steps (id)');
        $this->addSql('ALTER TABLE modification_requests ADD CONSTRAINT FK_46C9571DA76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE modification_requests ADD CONSTRAINT FK_46C9571D3E030ACD FOREIGN KEY (application_id) REFERENCES applications (id)');
        $this->addSql('ALTER TABLE modification_requests ADD CONSTRAINT FK_46C9571D642B8210 FOREIGN KEY (admin_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE preferences ADD CONSTRAINT FK_E931A6F5A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE program_requirements ADD CONSTRAINT FK_331B528D3EB8070A FOREIGN KEY (program_id) REFERENCES programs (id)');
        $this->addSql('ALTER TABLE programs ADD CONSTRAINT FK_F14965458565851 FOREIGN KEY (establishment_id) REFERENCES establishments (id)');
        $this->addSql('ALTER TABLE qualifications ADD CONSTRAINT FK_6765324C6B9DD454 FOREIGN KEY (user_profile_id) REFERENCES user_profiles (id)');
        $this->addSql('ALTER TABLE shortlists ADD CONSTRAINT FK_35C4212BA76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE shortlists ADD CONSTRAINT FK_35C4212B3EB8070A FOREIGN KEY (program_id) REFERENCES programs (id)');
        $this->addSql('ALTER TABLE shortlists ADD CONSTRAINT FK_35C4212B8565851 FOREIGN KEY (establishment_id) REFERENCES establishments (id)');
        $this->addSql('ALTER TABLE shortlists ADD CONSTRAINT FK_35C4212B6B9DD454 FOREIGN KEY (user_profile_id) REFERENCES user_profiles (id)');
        $this->addSql('ALTER TABLE suggestions ADD CONSTRAINT FK_91B68614A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE translations ADD CONSTRAINT FK_C6B7DA87A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE user_final_step_status ADD CONSTRAINT FK_58BBA552A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE user_final_step_status ADD CONSTRAINT FK_58BBA552F09195D0 FOREIGN KEY (final_step_id) REFERENCES final_steps (id)');
        $this->addSql('ALTER TABLE user_profiles ADD CONSTRAINT FK_6BBD6130A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE agent_assignments DROP FOREIGN KEY FK_A0440B9DCB944F1A');
        $this->addSql('ALTER TABLE agent_assignments DROP FOREIGN KEY FK_A0440B9D3414710B');
        $this->addSql('ALTER TABLE agent_assignments DROP FOREIGN KEY FK_A0440B9D3E030ACD');
        $this->addSql('ALTER TABLE ambassadors DROP FOREIGN KEY FK_67BE424CA76ED395');
        $this->addSql('ALTER TABLE application_documents DROP FOREIGN KEY FK_26B108893E030ACD');
        $this->addSql('ALTER TABLE application_documents DROP FOREIGN KEY FK_26B10889FC6B21F1');
        $this->addSql('ALTER TABLE application_steps DROP FOREIGN KEY FK_D7B6ED083E030ACD');
        $this->addSql('ALTER TABLE applications DROP FOREIGN KEY FK_F7C966F0A76ED395');
        $this->addSql('ALTER TABLE applications DROP FOREIGN KEY FK_F7C966F03EB8070A');
        $this->addSql('ALTER TABLE applications DROP FOREIGN KEY FK_F7C966F06B9DD454');
        $this->addSql('ALTER TABLE complaint_messages DROP FOREIGN KEY FK_C71B3714EDAE188E');
        $this->addSql('ALTER TABLE complaint_messages DROP FOREIGN KEY FK_C71B3714F624B39D');
        $this->addSql('ALTER TABLE complaints DROP FOREIGN KEY FK_A05AAF3AA76ED395');
        $this->addSql('ALTER TABLE document_translations DROP FOREIGN KEY FK_6B52FBF63430981D');
        $this->addSql('ALTER TABLE documents DROP FOREIGN KEY FK_A2B072886B9DD454');
        $this->addSql('ALTER TABLE final_step_documents DROP FOREIGN KEY FK_F1DCBC54F09195D0');
        $this->addSql('ALTER TABLE modification_requests DROP FOREIGN KEY FK_46C9571DA76ED395');
        $this->addSql('ALTER TABLE modification_requests DROP FOREIGN KEY FK_46C9571D3E030ACD');
        $this->addSql('ALTER TABLE modification_requests DROP FOREIGN KEY FK_46C9571D642B8210');
        $this->addSql('ALTER TABLE preferences DROP FOREIGN KEY FK_E931A6F5A76ED395');
        $this->addSql('ALTER TABLE program_requirements DROP FOREIGN KEY FK_331B528D3EB8070A');
        $this->addSql('ALTER TABLE programs DROP FOREIGN KEY FK_F14965458565851');
        $this->addSql('ALTER TABLE qualifications DROP FOREIGN KEY FK_6765324C6B9DD454');
        $this->addSql('ALTER TABLE shortlists DROP FOREIGN KEY FK_35C4212BA76ED395');
        $this->addSql('ALTER TABLE shortlists DROP FOREIGN KEY FK_35C4212B3EB8070A');
        $this->addSql('ALTER TABLE shortlists DROP FOREIGN KEY FK_35C4212B8565851');
        $this->addSql('ALTER TABLE shortlists DROP FOREIGN KEY FK_35C4212B6B9DD454');
        $this->addSql('ALTER TABLE suggestions DROP FOREIGN KEY FK_91B68614A76ED395');
        $this->addSql('ALTER TABLE translations DROP FOREIGN KEY FK_C6B7DA87A76ED395');
        $this->addSql('ALTER TABLE user_final_step_status DROP FOREIGN KEY FK_58BBA552A76ED395');
        $this->addSql('ALTER TABLE user_final_step_status DROP FOREIGN KEY FK_58BBA552F09195D0');
        $this->addSql('ALTER TABLE user_profiles DROP FOREIGN KEY FK_6BBD6130A76ED395');
        $this->addSql('DROP TABLE agent_assignments');
        $this->addSql('DROP TABLE ambassadors');
        $this->addSql('DROP TABLE application_documents');
        $this->addSql('DROP TABLE application_steps');
        $this->addSql('DROP TABLE applications');
        $this->addSql('DROP TABLE complaint_messages');
        $this->addSql('DROP TABLE complaints');
        $this->addSql('DROP TABLE document_translations');
        $this->addSql('DROP TABLE documents');
        $this->addSql('DROP TABLE establishments');
        $this->addSql('DROP TABLE faqs');
        $this->addSql('DROP TABLE final_step_documents');
        $this->addSql('DROP TABLE final_steps');
        $this->addSql('DROP TABLE modification_requests');
        $this->addSql('DROP TABLE parameters');
        $this->addSql('DROP TABLE preferences');
        $this->addSql('DROP TABLE program_requirements');
        $this->addSql('DROP TABLE programs');
        $this->addSql('DROP TABLE qualifications');
        $this->addSql('DROP TABLE services');
        $this->addSql('DROP TABLE shortlists');
        $this->addSql('DROP TABLE suggestions');
        $this->addSql('DROP TABLE test_vouchers');
        $this->addSql('DROP TABLE translations');
        $this->addSql('DROP TABLE `user`');
        $this->addSql('DROP TABLE user_final_step_status');
        $this->addSql('DROP TABLE user_profiles');
    }
}
